### ISSUE TITLE
Evaluation of Gun

### ISSUE THREAD

**Issue by rymnc** [status-im/codex-research#90]
[Gun](https://gun.eco/), is a decentralised p2p graph database. It could be useful to write an evaluation on it.

**Comment by markspanbroek** [comment]
Thanks! I like GUN, I played around with it a couple of years ago. From what I remember it had a very nice API for handling dynamic data. I don't think it had much protection against malicious behavior, nor any guarantees about how long data would stay in the network.

Doing an evaluation of GUN would make sense when we start designing dynamic data for Codex.
